version: '1.0'
services:
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'final_application'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: